spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://3.38.135.131:3306/checkmate-db
    url: jdbc:mysql://192.168.1.51:3306/checkmate-db
    username: checkmate-user
    password: check1324
jpa:
  hibernate:
    ddl-auto: create # ddl-auto

constant:
  value: value-prod
