spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://13.125.75.15:8080/checkmate-db
    url: jdbc:mysql://192.168.1.26:8080/checkmate-db
    username: checkmate-user
    password: check1324
  jpa:
    hibernate:
      ddl-auto: create # ddl-auto

constant:
  value: value-dev
