constant:
  value: value-h2
spring:
  h2.console:
    enabled: true
    web-allow-others: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/checkmate
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create