spring:
  profiles:
    default: me
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create # ddl-auto

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

server:
  port: 8081
