spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
#        database-platform: org.hibernate.dialect.MySQL8Dialect # mysql
    hibernate:
#            use-new-id-generator-mappings: false # mysql
      ddl-auto: create # ddl-auto

  #  mysql
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/test-db?serverTimezone=Asia/Seoul

logging.level:
  org.hibernate:
    SQL: debug
    type: trace
