# Workflow 의 이름 설정
name: Java CI with Gradle

# develop 브랜치에 대한 pr 이벤트가 일어났을 때 실행한다는 설정
on:
  pull_request:
    branches: [ main ]
    # PR 이 생성 되었을 때(opend), PR branch 에 새로운 commit 이 push 되었을 때(synchronize) 실행한다는 설정
    types: [opened, synchronize]

# 실행 해야 할 job 들에 대한 설정
jobs:
  # Job의 이름 설정, 빌드 수행
  build:
    # ubuntu 환경에서 실행, 환경은 GitHub 이 제공
    runs-on: ubuntu-latest
    # build job 의 세부 단계 설정
    steps:
      # 소스코드 체크아웃 수행
      - name: Checkout source code
#        uses: actions/checkout@v2
        uses: actions/checkout@main

      - name: Setup JDK 11
        uses: actions/setup-java@main
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: ./gradlew test
